---
version: '3'
services:
  repository:
    image: grid.repository:0.1
    build:
      context: .
      dockerfile: dockerfile.repository
    depends_on:
      - broker
    ports:
      - 22001:80
    environment:
      - Kafka__Hosts=broker:9092
      - ConnectionStrings__Postgres=Server=host.docker.internal;Port=5432;Database=Repository;User Id=repository;Password=12345678;
  scheduler:
    image: grid.scheduler:0.1
    build:
      context: .
      dockerfile: dockerfile.scheduler
    depends_on:
      - broker
      - repository
    ports:
      - 22000:80
    environment:
      - Kafka__Hosts=broker:9092
      - MatrixRepository__Host=http://repository:80
  worker:
    image: grid.worker:0.1
    build:
      context: .
      dockerfile: dockerfile.worker
    depends_on:
      - broker
    environment:
      - Kafka__Hosts=broker:9092

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.3.0
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1