apiVersion: v1
kind: Secret
metadata:
  name: postgres
type: Opaque
data:
  connection-string: U2VydmVyPWhvc3QuZG9ja2VyLmludGVybmFsO1BvcnQ9NTQzMjtEYXRhYmFzZT1SZXBvc2l0b3J5O1VzZXIgSWQ9cmVwb3NpdG9yeTtQYXNzd29yZD0xMjM0NTY3ODsK
